# Generated by Django 5.1.6 on 2025-02-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='paid',
        ),
    ]
