# Generated by Django 5.0.6 on 2025-03-03 04:28

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
